# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kH0vN3UjgzjYFBE2gXMS5Io99XLR2r_C
"""

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from recommender import ContentBasedRecommender
import os

app = FastAPI(title="Sistema de Recomendação de Filmes")

# Servir a interface index.html
app.mount("/static", StaticFiles(directory="."), name="static")

@app.get("/", include_in_schema=False)
def root():
    return FileResponse("index.html")

# Recomendação
caminho_csv = os.path.join(os.path.dirname(__file__), 'imdb_top_1000.csv')
recommender = ContentBasedRecommender(caminho_csv)

@app.get("/recomendar/{titulo}")
def recomendar_filmes(titulo: str):
    recomendacoes = recommender.recommend(titulo)
    if not recomendacoes:
        raise HTTPException(status_code=404, detail="Filme não encontrado.")
    return {"recomendados": recomendacoes}
