# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kH0vN3UjgzjYFBE2gXMS5Io99XLR2r_C
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from recommender import ContentBasedRecommender
import os

app = FastAPI(title="Sistema de Recomendação de Filmes")

# CORS (para permitir que HTML com JS chame a API)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Caminho para o CSV
caminho_csv = os.path.join(os.path.dirname(__file__), 'imdb_top_1000.csv')
recommender = ContentBasedRecommender(caminho_csv)

# Endpoint principal da interface
@app.get("/")
def serve_index():
    return FileResponse("index.html")

# Endpoint da recomendação
@app.get("/recomendar/{titulo}")
def recomendar_filmes(titulo: str):
    recomendacoes = recommender.recommend(titulo)
    if not recomendacoes:
        raise HTTPException(status_code=404, detail="Filme não encontrado.")
    return {"recomendados": recomendacoes}
