# -*- coding: utf-8 -*-
"""recommender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlJHuBpqLynCvYG0_c0voxEzAPqGfmvo
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

class ContentBasedRecommender:
    def __init__(self, movie_data_path):
        self.movies = pd.read_csv(movie_data_path)
        self.movies = self.movies[['Series_Title', 'Genre', 'Overview']].dropna()
        self._prepare()

    def _prepare(self):
        # Combina Gênero + Overview como base de conteúdo
        self.movies['content'] = self.movies['Genre'] + " " + self.movies['Overview']
        tfidf = TfidfVectorizer(stop_words='english')
        self.tfidf_matrix = tfidf.fit_transform(self.movies['content'])
        self.cosine_sim = linear_kernel(self.tfidf_matrix, self.tfidf_matrix)
        self.indices = pd.Series(self.movies.index, index=self.movies['Series_Title']).drop_duplicates()

    def recommend(self, title, top_n=5):
        idx = self.indices.get(title)
        if idx is None:
            return []
        sim_scores = list(enumerate(self.cosine_sim[idx]))
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
        movie_indices = [i[0] for i in sim_scores]
        return self.movies['Series_Title'].iloc[movie_indices].tolist()